anaxago_starter_registration:
    path:     /register
    controller: App\Controller\SecurityController::register

anaxago_starter_login:
    path:     /login
    controller: App\Controller\SecurityController::login